/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

export function configRead() {
    return invoke()<Config>("config_read")
}

export function configWrite(config: Config) {
    return invoke()<null>("config_write", { config })
}

export function scanStart() {
    return invoke()<null>("scan_start")
}

export type Config = { scan_dir: string[] }
